export const ADD_TO_CART = "ADD_TO_CART"
export const GET_TO_CART = "GET_TO_CART"
export const EMPTY_TO_CART = "EMPTY_TO_CART"

export const EMAIL_VARIFICATION ="EMAIL_VARIFICATION"
export const AUTH_LOGIN = "AUTH_LOGIN"

export const LOGIN_FORM = "LOGIN_FORM"
export const LOGED_FORM = "LOGED_FORM"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGGEDOUT_USER = "LOGGEDOUT_USER"

export const FORGOT_PASSWORD = "FORGOT_PASSWORD"

export const SET_ALERT = "SET_ALERT"
export const RESET_ALERT = "RESET_ALERT"

// CATEGORIES

export const GET_CATOGORIES = 'GET_CATOGORIES'
export const ADD_CATOGORIES = 'ADD_CATOGORIES'
export const UPDATE_CATOGORIES = 'UPDATE_CATOGORIES'
export const DELETE_CATOGORIES = 'DELETE_CATOGORIES'
export const ERROR_CATOGORIES = 'ERROR_CATOGORIES'

// PRODUCTS

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const ADD_PRODUCTS = 'ADD_PRODUCTS'
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS'
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS'
export const ERROR_PRODUCTS = 'ERROR_PRODUCTS'